// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPEYHgMGnhpaCuZGH0yKv3F89O4KsrjKI',
    appId: '1:676814841958:web:8bd4975d187585e23865a7',
    messagingSenderId: '676814841958',
    projectId: 'tarefasds20-777b9',
    authDomain: 'tarefasds20-777b9.firebaseapp.com',
    storageBucket: 'tarefasds20-777b9.firebasestorage.app',
    measurementId: 'G-H8C109M0MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2xFUsjg7wr0SuMzNzwJUQjp_RkWzCAPE',
    appId: '1:676814841958:android:6b52fc33e3cc1d1c3865a7',
    messagingSenderId: '676814841958',
    projectId: 'tarefasds20-777b9',
    storageBucket: 'tarefasds20-777b9.firebasestorage.app',
  );
}
